apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: web-pool
  annotations:
    # autoscaling.keda.sh/paused: "true"
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: k8s-web-pool
  minReplicaCount: 10
  maxReplicaCount: 10
  fallback:
    failureThreshold: 3
    replicas: 10
    behavior: currentReplicasIfHigher
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 30
          policies:
            - type: Percent
              value: 20
              periodSeconds: 15
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
      threshold: '16'
      query: sum(avg_over_time(envoy_cluster_upstream_cx_active{envoy_cluster_name="k8s-web-pool"}[1m]))
    metricType: Value
  
