apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: routing-envoy-metrics
  namespace: default
  labels:
    app: routing-envoy
    release: prometheus
spec:
  selector:
    matchLabels:
      app.zerodt.com/component: edge
  podMetricsEndpoints:
  - port: envoy-admin
    path: /stats/prometheus
    interval: 15s
    scrapeTimeout: 10s
