{
 "title": "Envoy Retry & Response Code SLI Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "ClusterName",
    "query": {
     "query": "label_values(envoy_cluster_upstream_rq_total,envoy_cluster_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "% of HTTP Status Served to Customers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "2xx",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (envoy_cluster_name) (\n  rate(envoy_cluster_upstream_rq{envoy_response_code=~\"2..|304\",envoy_cluster_name=~\"$ClusterName\"}[1m])\n)\n/\nsum by (envoy_cluster_name)(\n  rate(envoy_cluster_upstream_rq{envoy_cluster_name=~\"$ClusterName\"}[1m])\n)\n* 100",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "500",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (envoy_cluster_name) (\n  rate(envoy_cluster_upstream_rq{envoy_response_code=\"500\",envoy_cluster_name=~\"$ClusterName\"}[1m])\n)\n/\nsum by (envoy_cluster_name) (\n  rate(envoy_cluster_upstream_rq{envoy_cluster_name=~\"$ClusterName\"}[1m])\n)\n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "503",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (envoy_cluster_name) (\n  rate(envoy_cluster_upstream_rq{envoy_response_code=\"503\",envoy_cluster_name=~\"$ClusterName\"}[1m])\n)\n/\nsum by (envoy_cluster_name) (\n  rate(envoy_cluster_upstream_rq{envoy_cluster_name=~\"$ClusterName\"}[1m])\n)\n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "502",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (envoy_cluster_name) (\n  rate(envoy_cluster_upstream_rq{envoy_response_code=\"502\", envoy_cluster_name=~\"$ClusterName\"}[1m])\n)\n/\nsum by (envoy_cluster_name) (\n  rate(envoy_cluster_upstream_rq{envoy_cluster_name=~\"$ClusterName\"}[1m])\n)\n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "504",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (envoy_cluster_name) (\n  rate(envoy_cluster_upstream_rq{envoy_response_code=\"504\",envoy_cluster_name=~\"$ClusterName\"}[1m])\n)\n/\nsum by (envoy_cluster_name) (\n  rate(envoy_cluster_upstream_rq{envoy_cluster_name=~\"$ClusterName\"}[1m])\n)\n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total rps vs % of HTTP Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (envoy_response_code) (rate(envoy_cluster_upstream_rq{envoy_response_code=~\"[3-5]..\",envoy_response_code!=\"304\",envoy_cluster_name=~\"$ClusterName\"}[1m])) / on(envoy_cluster_name) group_left() sum(rate(envoy_cluster_upstream_rq{envoy_cluster_name=~\"$ClusterName\"}[1m])) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=~\"$ClusterName\"}[1m]))",
     "legendFormat": "rps"
    }
   ]
  },
  { "title": "HTTP Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "pXX - Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"$ClusterName\"}[5m])) by (le, envoy_cluster_name))",
     "legendFormat": "{{envoy_cluster_name}} 99%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"$ClusterName\"}[5m])) by (le,envoy_cluster_name))",
     "legendFormat": "{{envoy_cluster_name}} 95%"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"$ClusterName\"}[5m])) by (le,envoy_cluster_name))",
     "legendFormat": "{{envoy_cluster_name}} 50%"
    }
   ]
  },
  {
   "title": "sum: Total rq",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "avg(rate(envoy_cluster_upstream_rq_total[1m])) by (envoy_cluster_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "avg: Connections Active",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "expr": "avg by (envoy_cluster_name) (envoy_cluster_upstream_cx_active)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Dataplane Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "% Total Retries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (envoy_cluster_name) (rate(envoy_cluster_upstream_rq_retry{envoy_cluster_name=\"dataplane-web-global\"}[1m])) / sum by (envoy_cluster_name) (rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=\"dataplane-web-global\"}[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% Retry Success",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (envoy_cluster_name) (rate(envoy_cluster_upstream_rq_retry_success{envoy_cluster_name=\"dataplane-web-global\"}[1m])) / sum by (envoy_cluster_name) (rate(envoy_cluster_upstream_rq_retry{envoy_cluster_name=\"dataplane-web-global\"}[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Retry Limit Exceeded",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (envoy_cluster_name) (rate(envoy_cluster_upstream_rq_retry_limit_exceeded{envoy_cluster_name=\"dataplane-web-global\"}[1m])) ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}