apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: web-global
  annotations:
    # autoscaling.keda.sh/paused: "true"
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: core-web-global
  minReplicaCount: 4
  maxReplicaCount: 10
  fallback:
    failureThreshold: 3
    replicas: 8
    behavior: currentReplicasIfHigher
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 60
          policies:
            - type: Percent
              value: 20
              periodSeconds: 15
            - type: Pods
              value: 2
              periodSeconds: 15
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
      threshold: '2.5'
      query: avg(envoy_cluster_upstream_cx_active{envoy_cluster_name="core-web-global"})
    metricType: Value
  - type: cpu
    metricType: Utilization
    metadata:
      value: '50'
      containerName: app
  
